# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy to Prod server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:

    runs-on: [self-hosted, prod_server]

    steps:
    - uses: actions/checkout@v3
    - run: cp /var/www/app.therapydcm.com/secret/.env /var/www/app.therapydcm.com/actions-runner/_work/DCM-Client-Nextjs/DCM-Client-Nextjs/
    - run: npm ci
    - run: npm run build
    - run: pm2 restart dcm-client
